<a href="https://colab.research.google.com/github/caffonso/Control/blob/main/Control0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Atividade: ICP Biblioteca Numpy

In [ ]:
import numpy as np
print("Hi !")

Hi !


Atividade 1: Modifique o programa a seguir para escrever seu nome

In [ ]:
def PrintName():
# Modifique o programa para escrever seu nome    
# Começe aqui
  print("Carlla")
# termine aqui
  return

In [ ]:
PrintName()

Carlla


In [ ]:
def soma(a,b):    
  result = a + b  
  return(result)

In [ ]:
print(soma(3,2))

5


Atividade 2: Modifique o programa a seguir para relizar a subtração de dois números

In [ ]:
def subtract(a,b):
# começe aqui 
  result = (a-b)
# termine aqui     
  return(result)  

In [ ]:
print(subtract(5,3))

2


É possivel importar bibliotecas através do comando "import"
A biblioteca numpy é utilizada para calculos com vetores e matrizes

In [ ]:
import numpy as np
a = np.array([1, 2, 3, 4, 5, 6])
b = np.zeros((2,3))

In [ ]:
print(b)
print(a)

[[0. 0. 0.]
 [0. 0. 0.]]
[1 2 3 4 5 6]
